var annotated_dup =
[
    [ "ADCPeripheral", "class_a_d_c_peripheral.html", "class_a_d_c_peripheral" ],
    [ "AEADC", "class_a_e_a_d_c.html", "class_a_e_a_d_c" ],
    [ "AECircularBuffer", "class_a_e_circular_buffer.html", "class_a_e_circular_buffer" ],
    [ "AEDMA", "class_a_e_d_m_a.html", "class_a_e_d_m_a" ],
    [ "AEDMA_Channel", "class_a_e_d_m_a___channel.html", "class_a_e_d_m_a___channel" ],
    [ "AEDMA_Stream", "class_a_e_d_m_a___stream.html", "class_a_e_d_m_a___stream" ],
    [ "AEGPIOInput", "class_a_e_g_p_i_o_input.html", "class_a_e_g_p_i_o_input" ],
    [ "AEGPIOOutput", "class_a_e_g_p_i_o_output.html", "class_a_e_g_p_i_o_output" ],
    [ "AEITestLogData", "class_a_e_i_test_log_data.html", "class_a_e_i_test_log_data" ],
    [ "AENullClass", "class_a_e_null_class.html", "class_a_e_null_class" ],
    [ "AENULLEvent", "class_a_e_n_u_l_l_event.html", "class_a_e_n_u_l_l_event" ],
    [ "AENullFSMUtility", "class_a_e_null_f_s_m_utility.html", "class_a_e_null_f_s_m_utility" ],
    [ "AEPerformanceTimer", "class_a_e_performance_timer.html", "class_a_e_performance_timer" ],
    [ "AEPeripheral", "class_a_e_peripheral.html", "class_a_e_peripheral" ],
    [ "AEPin", "class_a_e_pin.html", "class_a_e_pin" ],
    [ "AEPort", "class_a_e_port.html", "class_a_e_port" ],
    [ "AEPortAndPin", "class_a_e_port_and_pin.html", "class_a_e_port_and_pin" ],
    [ "AESet", "class_a_e_set.html", "class_a_e_set" ],
    [ "AESetUpBase", "class_a_e_set_up_base.html", "class_a_e_set_up_base" ],
    [ "AETimerSimple", "class_a_e_timer_simple.html", "class_a_e_timer_simple" ],
    [ "AEUART", "class_a_e_u_a_r_t.html", "class_a_e_u_a_r_t" ],
    [ "ArrayCheckToMemCopy", "class_array_check_to_mem_copy.html", "class_array_check_to_mem_copy" ],
    [ "BoardVendorSetup", "class_board_vendor_setup.html", "class_board_vendor_setup" ],
    [ "ByteSerializer1", "class_byte_serializer1.html", "class_byte_serializer1" ],
    [ "ByteSerializer2", "class_byte_serializer2.html", "class_byte_serializer2" ],
    [ "ByteSerializer3", "class_byte_serializer3.html", "class_byte_serializer3" ],
    [ "ByteSerializer4", "class_byte_serializer4.html", "class_byte_serializer4" ],
    [ "ByteSerializer5", "class_byte_serializer5.html", "class_byte_serializer5" ],
    [ "ByteSerializer6", "class_byte_serializer6.html", "class_byte_serializer6" ],
    [ "GPIOInputPeripheral", "class_g_p_i_o_input_peripheral.html", "class_g_p_i_o_input_peripheral" ],
    [ "GPIOPeripheral", "class_g_p_i_o_peripheral.html", "class_g_p_i_o_peripheral" ],
    [ "GPIOSimType", "class_g_p_i_o_sim_type.html", "class_g_p_i_o_sim_type" ],
    [ "IsArrayChecker", "struct_is_array_checker.html", null ],
    [ "ModelType1Setup", "class_model_type1_setup.html", "class_model_type1_setup" ],
    [ "ModelType2Setup", "class_model_type2_setup.html", "class_model_type2_setup" ],
    [ "NULLPeripheral", "class_n_u_l_l_peripheral.html", "class_n_u_l_l_peripheral" ],
    [ "PinSelector", "class_pin_selector.html", "class_pin_selector" ],
    [ "SeriesSetup", "class_series_setup.html", "class_series_setup" ],
    [ "TypeChecker", "struct_type_checker.html", null ],
    [ "TypeChecker_isSame", "struct_type_checker__is_same.html", null ],
    [ "TypeChecker_isSame< TTypeToCheck1, TTypeToCheck1 >", "struct_type_checker__is_same_3_01_t_type_to_check1_00_01_t_type_to_check1_01_4.html", null ],
    [ "UARTConsole_InitTypeDef", "struct_u_a_r_t_console___init_type_def.html", "struct_u_a_r_t_console___init_type_def" ],
    [ "UARTPeripheral", "class_u_a_r_t_peripheral.html", "class_u_a_r_t_peripheral" ]
];