################################################ 
#this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
################################################




CREATE_TARGET_INTEGRATIONEXE(NAME_OF_TARGET ${INTEGRATION_TARGET_NAME}
LOCATION_OF_TARGET ${INTEGRATION_TARGET_DIRECTORY}
LibrariesToLinkTo AECoreLib 
LIST_OF_TESTS testSPB testFilters testAELoop testActionRequest testTDU testFSM
) 