//generated file: C:/AERTOS/AERTOS/src/AE/AECoreTests\testFilters.cpp
//**********************************************************************
//this is an auto-generated file using the template file located in the directory of C:\CodeGenerator\CodeGenerator\bin\Debug\..\..\FileTemplates\Files
//ONLY WRITE CODE IN THE UserCode_Section BLOCKS
//If you write code anywhere else,  it will be overwritten. modify the actual template file if needing to modify code outside usersection blocks.

//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################


 
#if INTEGRATION_TESTS_FOR_AECoreTests__testFilters
 
#include "IntegTestPipeline.h"


#include "AECore.h"
#include "AE_Init.h" 
#include "AEClock.h" 
#include "AEObjects.h" 

DECLARE_ALL_AO_PTR

static void clock1_callback(TimerHandle_t xTimerHandle);
static uint32_t sensor1_data[1];
static uint32_t sensor2_data[1];
static uint32_t sensor3_data[1];




//UserCode_Sectiona
//UserCode_Sectiona_end

void RunSelectedIntegrationTest_testFilters()
{

AE_Init();
 //UserCode_Sectionbeforemain
	AEITEST_END_TestsAfterTimer_AECoreTests(5000); 
	
	
#ifdef BOARD_USED__STM32F411RE
	GPIO_InitTypeDef gpiotim; 
	gpiotim.Pin = GPIO_PIN_1;
	gpiotim.Mode = GPIO_MODE_OUTPUT_PP;
	gpiotim.Pull = GPIO_NOPULL;
	gpiotim.Speed = GPIO_SPEED_HIGH;
	HAL_GPIO_Init(GPIOA, &gpiotim);
#endif
//UserCode_Sectionbeforemain_end

static AEClock<AEObservorSensor, AEObservorInterpretorBaseDUMMY, 3, 0, 0, 0, 0, 0,0, 0, 0,0, 0, 0,0, 0, 0,0, 0, 0,0, 0, 0> clock1L(100, clock1_callback);
clock1 = &clock1L;

static AEObservorSensorFilterOut< 2, Filter<DerivativeFilter, 2>,Filter<DerivativeFilter, 2> ,1  > sensor1L((uint32_t*) sensor1_data, SensorResolution::Resolution16Bit  );
sensor1 = &sensor1L;

static AEObservorSensorFilterOut< 2, Filter<DerivativeFilter, 2>,Filter<DerivativeFilter, 2> ,1  > sensor2L((uint32_t*) sensor2_data, SensorResolution::Resolution16Bit  );
sensor2 = &sensor2L;

static AEObservorSensorFilterOut< 2, Filter<DerivativeFilter, 2>,Filter<DerivativeFilter, 2> ,1  > sensor3L((uint32_t*) sensor3_data, SensorResolution::Resolution16Bit  );
sensor3 = &sensor3L;

static ThreeDimensionalVector< false> velocitySPBL; velocitySPBL.InitSPBObserver(StyleOfSPB::EachSPBTask); 
velocitySPB = &velocitySPBL;

static ThreeDimensionalVector< false> accelerationSPBL; accelerationSPBL.InitSPBObserver(StyleOfSPB::EachSPBTask); 
accelerationSPB = &accelerationSPBL;









//UserCode_Sectionbeforelinks
//UserCode_Sectionbeforelinks_end
static float velocitySPBchBuffer1[1];
velocitySPB->AddSignalFlowLinkToChannelWithCopy1(sensor1, velocitySPBchBuffer1, 1);
static float velocitySPBchBuffer2[1];
velocitySPB->AddSignalFlowLinkToChannelWithCopy2(sensor2, velocitySPBchBuffer2, 1);
static float velocitySPBchBuffer3[1];
velocitySPB->AddSignalFlowLinkToChannelWithCopy3(sensor3, velocitySPBchBuffer3, 1);
static float accelerationSPBchBuffer1[1];
accelerationSPB->AddSignalFlowLinkToChannelWithCopy1(sensor1, accelerationSPBchBuffer1, 2);
static float accelerationSPBchBuffer2[1];
accelerationSPB->AddSignalFlowLinkToChannelWithCopy2(sensor2, accelerationSPBchBuffer2, 2);
static float accelerationSPBchBuffer3[1];
accelerationSPB->AddSignalFlowLinkToChannelWithCopy3(sensor3, accelerationSPBchBuffer3, 2);


//UserCode_Sectionbeforeclock
//UserCode_Sectionbeforeclock_end
clock1->SetObservorToClock(sensor1, AEClock_PrescalerEnum::PRESCALER1);
clock1->SetObservorToClock(sensor2, AEClock_PrescalerEnum::PRESCALER1);
clock1->SetObservorToClock(sensor3, AEClock_PrescalerEnum::PRESCALER1);


//AEITEST_END_TestsAfterTimer_AECoreTests(5000);
//UserCode_Sectionb
	velocitySPB->UserInitialize(true);
	accelerationSPB->UserInitialize(false);
//UserCode_Sectionb_end

AEAO::ConfigureAndStart();
}


//UserCode_Sectionc
//UserCode_Sectionc_end


static void clock1_callback(TimerHandle_t xTimerHandle) {  
  //UserCode_Sectionclock1before
	sensor1_data[0] = sensor1_data[0] > 90000 ? 1 : (sensor1_data[0] + 1);
	sensor2_data[0] = sensor2_data[0] > 90000 ? 1 : (sensor2_data[0] + 2);
	sensor3_data[0] = sensor3_data[0] > 90000 ? 1 : (sensor3_data[0] + 3);
//UserCode_Sectionclock1before_end 
  
 clock1->Tick(); 
  //UserCode_Sectionclock1after
//UserCode_Sectionclock1after_end 
}


#endif