//generated file: C:/AERTOS/AERTOS/src/AE/AECoreTests\testTDU.cpp
//**********************************************************************
//this is an auto-generated file using the template file located in the directory of C:\CodeGenerator\CodeGenerator\bin\Debug\..\..\FileTemplates\Files
//ONLY WRITE CODE IN THE UserCode_Section BLOCKS
//If you write code anywhere else,  it will be overwritten. modify the actual template file if needing to modify code outside usersection blocks.

//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################


 
#if INTEGRATION_TESTS_FOR_AECoreTests__testTDU
 
#include "IntegTestPipeline.h"


#include "AECore.h"
#include "AE_Init.h" 
#include "AEClock.h" 
#include "AEObjects.h" 

DECLARE_ALL_AO_PTR

static void clockforTdu_cb(TimerHandle_t xTimerHandle);
#include "AELoopObjectTest3.h"
static AELoopObjectTest3* objectTest1;
#include "AELoopObjectTest4.h"
static AELoopObjectTest4* objectTest2;




//UserCode_Sectiona
//UserCode_Sectiona_end

void RunSelectedIntegrationTest_testTDU()
{

AE_Init();
 //UserCode_Sectionbeforemain
	
	AEITEST_END_TestsAfterTimer_AECoreTests(5000); 
	AEITEST_EXPECT_TEST_TO_RUN_AECoreTests("TDUWaitForEvent");
	
//UserCode_Sectionbeforemain_end


static AEClock<AEObservorSensorDUMMY, AEObservorInterpretorBaseDUMMY, 0, 0, 1, 0, 0, 0,0, 0, 0,0, 0, 0,0, 0, 0,0, 0, 0,0, 0, 0> clockforTduL(1000, clockforTdu_cb);
clockforTdu = &clockforTduL;

static UARTDriverTDU uartDriverTDU_L; uartDriverTDU_L.Init(AEPriorities::MediumPriority);
uartDriverTDU = &uartDriverTDU_L;


static AELoopObjectTest3 objectTest1_l;
objectTest1 = &objectTest1_l;
objectTest1->InitObject(20, AEPriorities::MediumPriority);

static AELoopObjectTest4 objectTest2_l;
objectTest2 = &objectTest2_l;
objectTest2->InitObject(3, AEPriorities::MediumPriority);



//UserCode_Sectionbeforelinks
//UserCode_Sectionbeforelinks_end


//UserCode_Sectionbeforeclock
//UserCode_Sectionbeforeclock_end
clockforTdu->SetTDUToClock(uartDriverTDU, AEClock_PrescalerEnum::PRESCALER1);


//AEITEST_END_TestsAfterTimer_AECoreTests(5000);
//UserCode_Sectionb
//UserCode_Sectionb_end

AEAO::ConfigureAndStart();
}


//UserCode_Sectionc
//UserCode_Sectionc_end


static void clockforTdu_cb(TimerHandle_t xTimerHandle) {  
  //UserCode_SectionclockforTdubefore
//UserCode_SectionclockforTdubefore_end 
  
 clockforTdu->Tick(); 
  //UserCode_SectionclockforTduafter
//UserCode_SectionclockforTduafter_end 
}


#endif