//generated file: C:/AERTOS/AERTOS/src/AE/AECoreTests\include\AELoopObjectTest5.h
//**********************************************************************
//this is an auto-generated file using the template file located in the directory of C:\CodeGenerator\CodeGenerator\bin\Debug\..\..\FileTemplates\Files
//ONLY WRITE CODE IN THE UserCode_Section BLOCKS
//If you write code anywhere else,  it will be overwritten. modify the actual template file if needing to modify code outside usersection blocks.

//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################

#pragma once
 
#include "AELoopObject.h" 
#include  "AEObjects.h"   

//UserCode_Sectionheader
extern int StateTracker;
//UserCode_Sectionheader_end

class AELoopObjectTest5 : public AELoopObject
{
	
public:
	AELoopObjectTest5() { 
		  //UserCode_Sectionctor
		swapperind = 0;
//UserCode_Sectionctor_end
	} 
	
 //UserCode_Sectionpublic
	int swapperind;
//UserCode_Sectionpublic_end
	


protected: 
	
		void StartAOLoopObject()  override
	{
//		AELoopSubscribe(Button1, AELoopObject1Test, Button1_Callback);
		//UserCode_Sectionstartae
//UserCode_Sectionstartae_end
	}
	
	void Update() override {
		
		//UserCode_Sectionupdate

		if (swapperind == 0)
		{
			//AEITEST_AECoreTestEXE("FirstState", StateTracker == 0, "initially StateTracker is 0")
			AEITEST_AECoreTests("FirstState", StateTracker == 10, "initially BlindsUI FSM is in idle state")
			PublishEvt(&Button1_Instance );
		}
		else if (swapperind == 1)
		{
			AEITEST_AECoreTests("SecondState", StateTracker == 20, "ConfigBlindsUI FSM is in idle state")
			PublishEvt(&Button3_Instance);	
		}
		else if (swapperind == 2)
		{
			AEITEST_AECoreTests("ThirdState", StateTracker == 30, "ConfigBlindsUI FSM is in SettingTopLimit state")
			PublishEvt(&Button3_Instance);	
		}		
		else if (swapperind == 3)
		{
			AEITEST_AECoreTests("FourthState", StateTracker == 40, "ConfigBlindsUI FSM is in SettingBottomLimit state")
			PublishEvt(&Button3_Instance);	 
		}
		else if (swapperind == 4)
		{ 
			PublishEvt(&Button3_Instance);	 
		}
		else if (swapperind == 5)
		{
			AEITEST_AECoreTests("fifthState", StateTracker == 10, "ConfigBlindsUI FSM Has left and entered BlindsUI FSM idle state")
			PublishEvt(&Button2_Instance);	
			//PublishEvt(&Button2_Sig_Instance);	
		}
		else if (swapperind == 6)
		{
			AEITEST_AECoreTests("sixthState", StateTracker == 50, "ConfigBlindsUI FSM Has left and entered BlindsUI FSM idle state")
			
			//PublishEvt(&Button2_Sig_Instance);	
		}
		
		//swapperind = swapperind > 5 ?  0 : (swapperind +1);
		swapperind++;
		
//UserCode_Sectionupdate_end
		 
	} 
	
	//UserCode_Sectionprotect
//UserCode_Sectionprotect_end
	
};


//UserCode_Sectionfuncs
//UserCode_Sectionfuncs_end