//generated file: C:/AERTOS/AERTOS/src/AE/AECoreTests\include\AELoopObjectTest2.h
//**********************************************************************
//this is an auto-generated file using the template file located in the directory of C:\CodeGenerator\CodeGenerator\bin\Debug\..\..\FileTemplates\Files
//ONLY WRITE CODE IN THE UserCode_Section BLOCKS
//If you write code anywhere else,  it will be overwritten. modify the actual template file if needing to modify code outside usersection blocks.

//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################

#pragma once
 
#include "AELoopObject.h" 
#include  "AEObjects.h"   

//UserCode_Sectionheader
//UserCode_Sectionheader_end

class AELoopObjectTest2 : public AELoopObject
{
	
public:
	AELoopObjectTest2() { 
		  //UserCode_Sectionctor
//UserCode_Sectionctor_end
	} 
	
 //UserCode_Sectionpublic
//UserCode_Sectionpublic_end
	


protected: 
	
		void StartAOLoopObject()  override
	{
//		AELoopSubscribe(Button1, AELoopObject1Test, Button1_Callback);
		//UserCode_Sectionstartae
//UserCode_Sectionstartae_end
	}
	
	void Update() override {
		
		//UserCode_Sectionupdate 
		AEStartTimer(1); 
		uartDriver->Transmit(this->GetAO_ID(), "hello from uuart service\n");  
//UserCode_Sectionupdate_end
		 
	} 
	
	//UserCode_Sectionprotect
//UserCode_Sectionprotect_end
	
};


//UserCode_Sectionfuncs
//UserCode_Sectionfuncs_end