//generated file: C:/AERTOS/AERTOS/src/AE/AECoreTests\include\AELoopObjectTest.h
//**********************************************************************
//this is an auto-generated file using the template file located in the directory of C:\CodeGenerator\CodeGenerator\bin\Debug\..\..\FileTemplates\Files
//ONLY WRITE CODE IN THE UserCode_Section BLOCKS
//If you write code anywhere else,  it will be overwritten. modify the actual template file if needing to modify code outside usersection blocks.

//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################

#pragma once
 
#include "AELoopObject.h" 
#include  "AEObjects.h"   

//UserCode_Sectionheader
//UserCode_Sectionheader_end

class AELoopObjectTest : public AELoopObject
{
	
public:
	AELoopObjectTest() { 
		  //UserCode_Sectionctor
//UserCode_Sectionctor_end
	} 
	
 //UserCode_Sectionpublic
//UserCode_Sectionpublic_end
	


protected: 
	
		void StartAOLoopObject()  override
	{
//		AELoopSubscribe(Button1, AELoopObject1Test, Button1_Callback);
		//UserCode_Sectionstartae
//UserCode_Sectionstartae_end
	}
	
	void Update() override {
		
		//UserCode_Sectionupdate
		counter++;
		
		if (counter > 5)
		{
			
			AEITEST_AECoreTests("Looponce", true, "looped once");
		}

		//do some busy work
		uint32_t aff = 0;
		for (uint32_t i = 0; i < ToCountTo; i++)
		{
			aff++;
		}  
//UserCode_Sectionupdate_end
		 
	} 
	
	//UserCode_Sectionprotect
#ifndef SWIL_HWIL_DRIVEN__HWIL
	const uint32_t ToCountTo = 10000000;
#else
	const uint32_t ToCountTo = 20000;
#endif
  
	uint32_t counter;
//UserCode_Sectionprotect_end
	
};


//UserCode_Sectionfuncs
//UserCode_Sectionfuncs_end