//generated file: C:/AERTOS/AERTOS/src/AE/AECoreTests\include\NormalOperationFSM.h
//**********************************************************************
//this is an auto-generated file using the template file located in the directory of C:\CodeGenerator\CodeGenerator\bin\Debug\..\..\FileTemplates\Files
//ONLY WRITE CODE IN THE UserCode_Section BLOCKS
//If you write code anywhere else,  it will be overwritten. modify the actual template file if needing to modify code outside usersection blocks.

//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################

#pragma once
 
#include "AEClock.h"

#include "AESimpleFSM.h"
 
#include "AEEventBase.h" 

 

//UserCode_Sectionheader
extern int StateTracker;

//UserCode_Sectionheader_end
 

class NormalOperationFSM : public AESimpleFSM<NormalOperationFSM>
{
public:
	NormalOperationFSM() 
	{
	//UserCode_Sectionctor
//UserCode_Sectionctor_end
	};

	//UserCode_Sectionpublic
//UserCode_Sectionpublic_end

	static AETransitionType Idle(TypeOfThisFSM* const thisFSM, AEEventDiscriminator_t const * const evt);
static AETransitionType MovingToPoint(TypeOfThisFSM* const thisFSM, AEEventDiscriminator_t const * const evt);
 


	// Inherited via AESimpleFSM
	StateFuncPtr InitialState() override;
	
protected:

	//UserCode_Sectionprot
//UserCode_Sectionprot_end

};


//UserCode_Sectionfunc
//UserCode_Sectionfunc_end
 



//state: Idle ======================================================
inline AETransitionType NormalOperationFSM::Idle(TypeOfThisFSM * const thisFSM, AEEventDiscriminator_t const * const evt)
{
	AETransitionType transitionType = UNHANDLED;

	//UserCode_SectionIdlea
//UserCode_SectionIdlea_end
	
	
	auto evtId = evt->GetEvtID();
	switch (evtId)
	{
	case Enter_Sig:
	{
         thisFSM->Subscribe<Button1>();
         thisFSM->Subscribe<Button2>();
         thisFSM->Subscribe<Button3>();
 
		
	//UserCode_SectionIdleenter
		StateTracker = 50;
//UserCode_SectionIdleenter_end
		 
		 
		break;
	}
	case Exit_Sig:
	{
          thisFSM->UnSubscribe<Button1>();
          thisFSM->UnSubscribe<Button2>();
          thisFSM->UnSubscribe<Button3>();
 
		
	//UserCode_SectionIdleexit
//UserCode_SectionIdleexit_end
		
		break;
	}
	

// Button1 ------------------------------------------------------------
    case Button1:
     {
    //UserCode_SectionIdleButton1
	     AEPrint("\nNormalUserOperationBlindsFSM:  Idle:Button1\n"); 
//UserCode_SectionIdleButton1_end
        break;
     }


// Button2 ------------------------------------------------------------
    case Button2:
     {
    //UserCode_SectionIdleButton2
	     AEPrint("\nNormalUserOperationBlindsFSM:  Idle:Button2\n"); 
//UserCode_SectionIdleButton2_end
        break;
     }


// Button3 ------------------------------------------------------------
    case Button3:
     {
    //UserCode_SectionIdleButton3
	     AEPrint("\nNormalUserOperationBlindsFSM:  Idle:Button3\n"); 
//UserCode_SectionIdleButton3_end
        TRANSITION_TOSTATE(&MovingToPoint)
        break;
     }

 
	
	default:
		break;
	}

	return transitionType;
}


//state: MovingToPoint ======================================================
inline AETransitionType NormalOperationFSM::MovingToPoint(TypeOfThisFSM * const thisFSM, AEEventDiscriminator_t const * const evt)
{
	AETransitionType transitionType = UNHANDLED;

	//UserCode_SectionMovingToPointa
//UserCode_SectionMovingToPointa_end
	
	
	auto evtId = evt->GetEvtID();
	switch (evtId)
	{
	case Enter_Sig:
	{
         thisFSM->Subscribe<Button1>();
         thisFSM->Subscribe<Button2>();
         thisFSM->Subscribe<Button3>();
 
		
	//UserCode_SectionMovingToPointenter
//UserCode_SectionMovingToPointenter_end
		 
		 
		break;
	}
	case Exit_Sig:
	{
          thisFSM->UnSubscribe<Button1>();
          thisFSM->UnSubscribe<Button2>();
          thisFSM->UnSubscribe<Button3>();
 
		
	//UserCode_SectionMovingToPointexit
//UserCode_SectionMovingToPointexit_end
		
		break;
	}
	

// Button1 ------------------------------------------------------------
    case Button1:
     {
    //UserCode_SectionMovingToPointButton1
	     AEPrint("\NormalUserOperationBlindsFSM:  MovingToPoint:Button1\n");
//UserCode_SectionMovingToPointButton1_end
        break;
     }


// Button2 ------------------------------------------------------------
    case Button2:
     {
    //UserCode_SectionMovingToPointButton2
	     AEPrint("\NormalUserOperationBlindsFSM:  MovingToPoint:Button2\n");
//UserCode_SectionMovingToPointButton2_end
        break;
     }


// Button3 ------------------------------------------------------------
    case Button3:
     {
    //UserCode_SectionMovingToPointButton3
	     AEPrint("\NormalUserOperationBlindsFSM:  MovingToPoint:Button3\n");
//UserCode_SectionMovingToPointButton3_end
        TRANSITION_TOSTATE(&Idle)
        break;
     }

 
	
	default:
		break;
	}

	return transitionType;
} 


inline NormalOperationFSM::StateFuncPtr NormalOperationFSM::InitialState()
{
	return CastToStateFuncPtr(&Idle);
}
