//generated file: C:/AERTOS/AERTOS/src/AE/AECoreTests\include\PID_SPB.h
//**********************************************************************
//this is an auto-generated file using the template file located in the directory of C:\CodeGenerator\CodeGenerator\bin\Debug\..\..\FileTemplates\Files
//ONLY WRITE CODE IN THE UserCode_Section BLOCKS
//If you write code anywhere else,  it will be overwritten. modify the actual template file if needing to modify code outside usersection blocks.

//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################

#pragma once


#include "AESPBObservorOutputType.h"
#include "AEUtils.h"
#include "FreeRTOS.h"
#include "AEFilter.h"

#include "AEIntegrationTesting.h"

//UserCode_Sectionheader
//UserCode_Sectionheader_end

template<bool isSubscribable, uint32_t CHANNEL_CONSUMPTION_SIZE1, TEMPLATESPB_Filters>
	class PID_SPB :
		public AESPBObservorOutputType <1, 1, isSubscribable,
TEMPLATESPB_FilterParams>
	{
	public:
		PID_SPB();
		
		//UserCode_Sectionpublic
//UserCode_Sectionpublic_end


	protected: uint8_t kpfrom0to100; 
public: uint8_t  Getkpfrom0to100()   const {return kpfrom0to100; }

protected: uint8_t kifrom0to100; 
public: uint8_t  Getkifrom0to100()   const {return kifrom0to100; }

protected: uint8_t kdfrom0to100; 
public: uint8_t  Getkdfrom0to100()   const {return kdfrom0to100; }

protected: float maxPossibleError; 
public: float  GetmaxPossibleError()   const {return maxPossibleError; }

protected: float maxpossibleRateOfChangeOfControlVariable; 
public: float  GetmaxpossibleRateOfChangeOfControlVariable()   const {return maxpossibleRateOfChangeOfControlVariable; }

protected: float desiredInput; 
public: float  GetdesiredInput()   const {return desiredInput; }

protected: float mapOutputTOMin; 
public: float  GetmapOutputTOMin()   const {return mapOutputTOMin; }

protected: float mapOutputTOMax; 
public: float  GetmapOutputTOMax()   const {return mapOutputTOMax; }

protected: float offsetFromZero; 
public: float  GetoffsetFromZero()   const {return offsetFromZero; }


public: void UserInitialize(uint8_t _kpfrom0to100 , uint8_t _kifrom0to100 , uint8_t _kdfrom0to100 , float _maxPossibleError , float _maxpossibleRateOfChangeOfControlVariable , float _desiredInput , float _mapOutputTOMin  = -100000, float _mapOutputTOMax  = 100000, float _offsetFromZero  = 0)
	{
		kpfrom0to100 =  _kpfrom0to100;
kifrom0to100 =  _kifrom0to100;
kdfrom0to100 =  _kdfrom0to100;
maxPossibleError =  _maxPossibleError;
maxpossibleRateOfChangeOfControlVariable =  _maxpossibleRateOfChangeOfControlVariable;
desiredInput =  _desiredInput;
mapOutputTOMin =  _mapOutputTOMin;
mapOutputTOMax =  _mapOutputTOMax;
offsetFromZero =  _offsetFromZero;

		
		//UserCode_SectionuserInited
//UserCode_SectionuserInited_end
		
		userInitialized = true;
	}
private: bool userInitialized = false;
protected: void CheckIfConfiguredProperly() const override  
	{
		//PID_SPB::CheckIfConfiguredProperly();
		if (userInitialized == false)
		{
			// you did not initialize one of your AEobjects
			AEAssertRuntime(userInitialized == true, "user did not call the UserInitailize function for  PID_SPB"); 
		} 
		 
	}
	
	private:
	//UserCode_Sectionprivate
//UserCode_Sectionprivate_end

		void RefreshOVERRIDE(float OutputSignal[1]) override;

	};


//UserCode_Sectionfunc
//UserCode_Sectionfunc_end


template<bool isSubscribable, uint32_t CHANNEL_CONSUMPTION_SIZE1, TEMPLATESPB_FiltersFunctionParams>
	inline PID_SPB< isSubscribable,  CHANNEL_CONSUMPTION_SIZE1, TEMPLATESPB_FilterParams>::PID_SPB()
	{
		//UserCode_Sectionctor
//UserCode_Sectionctor_end
	}

template<bool isSubscribable, uint32_t CHANNEL_CONSUMPTION_SIZE1, TEMPLATESPB_FiltersFunctionParams>
	inline void PID_SPB< isSubscribable,  CHANNEL_CONSUMPTION_SIZE1, TEMPLATESPB_FilterParams>::RefreshOVERRIDE(float OutputSignal[1])
	{

		float* ch1 = this->InputChannels[0]->ChannelSignalBufferSingle; 

 
		//UserCode_Sectionrefresh
//UserCode_Sectionrefresh_end
	}

