//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################


#define UARTDriverTDU_Transmit_CTOR ActionReq1.SetServiceFunc([](UARTDriverTDU* p, char const* msg){p->_Transmit( msg); });


//Transmit----------------------------------------------

	  
	  
	#define UARTDriverTDU_Transmit_Service \
	inline void Transmit(int idOfAO, char const* msg)\
	{\
		this->RunRequest1(idOfAO,  msg); \
	}\
	\
	inline Token* Transmit_WithWait(int idOfAO, char const* msg)\
	{\
		return this->RunRequestWithWait1(idOfAO,  msg); \
	}\
	\
	inline Action1_RETURNTYPE_t Transmit_WaitForRequestToFinish(Token* token)\
	{\
		return this->WaitForRequestToFinish1(token  ); \
	}\
	\
	inline void Transmit_DoneWithRequest(Token* tokenOfRequest)\
	{\
		return this->DoneWithRequest1(tokenOfRequest); \
	}\
	inline Action1_RETURNTYPE_t Transmit_WaitHereForFinish(int idOfAO, char const* msg)\
	{\
		auto token = this->RunRequestWithWait1(idOfAO,  msg);\
		Action1_RETURNTYPE_t ret = this->WaitForRequestToFinish1(token);\
		this->DoneWithRequest1(token);\
		return ret;\
	}
	
	#define UARTDriverTDU_Transmit void _Transmit(int idOfAO, char const* msg)
	#define UARTDriverTDU_Transmit_Update bool _TransmitUpdate(ActionRequestObjectArgTDU-2* actReq, char const* msg)   
#define UARTDriverTDU_TransmitTDU_CTOR ActionReq4.SetServiceFunc([](UARTDriverTDU* p, char const* msg){p->_TransmitTDU( msg); });ActionReq4.SetUpdateFunc([](UARTDriverTDU* p, char const* msg) {return p->_TransmitTDUUpdate(&p->ActionReq4,  msg); });


//TransmitTDU----------------------------------------------

	  
	  
	#define UARTDriverTDU_TransmitTDU_Service \
	inline void TransmitTDU(int idOfAO, char const* msg)\
	{\
		this->RunRequest4(idOfAO,  msg); \
	}\
	\
	inline Token* TransmitTDU_WithWait(int idOfAO, char const* msg)\
	{\
		return this->RunRequestWithWait4(idOfAO,  msg); \
	}\
	\
	inline Action4_RETURNTYPE_t TransmitTDU_WaitForRequestToFinish(Token* token)\
	{\
		return this->WaitForRequestToFinish4(token  ); \
	}\
	\
	inline void TransmitTDU_DoneWithRequest(Token* tokenOfRequest)\
	{\
		return this->DoneWithRequest4(tokenOfRequest); \
	}\
	inline Action4_RETURNTYPE_t TransmitTDU_WaitHereForFinish(int idOfAO, char const* msg)\
	{\
		auto token = this->RunRequestWithWait4(idOfAO,  msg);\
		Action4_RETURNTYPE_t ret = this->WaitForRequestToFinish4(token);\
		this->DoneWithRequest4(token);\
		return ret;\
	}
	
	#define UARTDriverTDU_TransmitTDU void _TransmitTDU(int idOfAO, char const* msg)
	#define UARTDriverTDU_TransmitTDU_Update bool _TransmitTDUUpdate(ActionRequestObjectArgTDU1* actReq, char const* msg)   
//Alldefines ------------------
#define UARTDriverTDU_CTOR \
UARTDriverTDU_Transmit_CTOR \
UARTDriverTDU_TransmitTDU_CTOR 
#define UARTDriverTDU_Service \
UARTDriverTDU_Transmit_Service \
UARTDriverTDU_TransmitTDU_Service 
