

//
#include "AEGPIOOutput.h"
#include "AEGPIOInput.h"
#include "AEADC.h"
#include "AEUART.h"
#include "AEI2C.h"
#include "AESPI.h"
#include "AEPWM.h"

#ifdef GPIOPERIPHERAL1
GPIOPERIPHERAL1 *GPIOPERIPHERAL1_Instance = GPIOPERIPHERAL1::getInstance();
AEGPIOOutput *GPIOPERIPHERAL1_Name = nullptr;
//GPIOPERIPHERAL1 *GPIOPERIPHERAL1_Instance = GPIOPERIPHERAL1::getInstance();
#endif
#ifdef GPIOPERIPHERAL2
GPIOPERIPHERAL2 *GPIOPERIPHERAL2_Instance = GPIOPERIPHERAL2::getInstance();
AEGPIOOutput *GPIOPERIPHERAL2_Name = nullptr;
#endif
#ifdef GPIOPERIPHERAL3
GPIOPERIPHERAL3 *GPIOPERIPHERAL3_Instance = GPIOPERIPHERAL3::getInstance();
AEGPIOOutput *GPIOPERIPHERAL3_Name = nullptr;
#endif
#ifdef GPIOPERIPHERAL4
GPIOPERIPHERAL4 *GPIOPERIPHERAL4_Instance = GPIOPERIPHERAL4::getInstance();
AEGPIOOutput *GPIOPERIPHERAL4_Name = nullptr;
#endif
#ifdef GPIOPERIPHERAL5
GPIOPERIPHERAL5 *GPIOPERIPHERAL5_Instance = GPIOPERIPHERAL5::getInstance();
AEGPIOOutput *GPIOPERIPHERAL5_Name = nullptr;
#endif
#ifdef GPIOPERIPHERAL6 
GPIOPERIPHERAL6 *GPIOPERIPHERAL6_Instance = GPIOPERIPHERAL6::getInstance();
AEGPIOOutput *GPIOPERIPHERAL6_Name = nullptr;
#endif


#ifdef GPIOInputPERIPHERAL1
GPIOInputPERIPHERAL1* GPIOInputPERIPHERAL1_Instance = GPIOInputPERIPHERAL1::getInstance();  
AEGPIOInput *GPIOInputPERIPHERAL1_Name = nullptr;
//GPIOPERIPHERAL1 *GPIOPERIPHERAL1_Instance = GPIOPERIPHERAL1::getInstance();
#endif
#ifdef GPIOInputPERIPHERAL2
GPIOInputPERIPHERAL2* GPIOInputPERIPHERAL2_Instance = GPIOInputPERIPHERAL2::getInstance();  
AEGPIOInput *GPIOInputPERIPHERAL2_Name = nullptr;
#endif
#ifdef GPIOInputPERIPHERAL3
GPIOInputPERIPHERAL3* GPIOInputPERIPHERAL3_Instance = GPIOInputPERIPHERAL3::getInstance();  
AEGPIOInput *GPIOInputPERIPHERAL3_Name = nullptr;
#endif
#ifdef GPIOInputPERIPHERAL4
GPIOInputPERIPHERAL4* GPIOInputPERIPHERAL4_Instance = GPIOInputPERIPHERAL4::getInstance();  
AEGPIOInput *GPIOInputPERIPHERAL4_Name = nullptr;
#endif
#ifdef GPIOInputPERIPHERAL5 
GPIOInputPERIPHERAL5* GPIOInputPERIPHERAL5_Instance = GPIOInputPERIPHERAL5::getInstance();  
AEGPIOInput *GPIOInputPERIPHERAL5_Name = nullptr;
#endif
#ifdef GPIOInputPERIPHERAL6
GPIOInputPERIPHERAL6* GPIOInputPERIPHERAL6_Instance = GPIOInputPERIPHERAL6::getInstance();  
AEGPIOInput *GPIOInputPERIPHERAL6_Name = nullptr;
#endif






#ifdef ADCPERIPHERAL1
ADCPERIPHERAL1* ADCPERIPHERAL1_Instance = ADCPERIPHERAL1::getInstance();  

AEADC *ADCPERIPHERAL1_Name_CH1 = nullptr;  
 
#ifdef ADCPERIPHERAL1_Name_CH2
AEADC *ADCPERIPHERAL1_Name_CH2 = nullptr; 
#endif

#ifdef ADCPERIPHERAL1_Name_CH3
AEADC *ADCPERIPHERAL1_Name_CH3 = nullptr; 
#endif

#ifdef ADCPERIPHERAL1_Name_CH4
AEADC *ADCPERIPHERAL1_Name_CH4 = nullptr; 
#endif

#ifdef ADCPERIPHERAL1_Name_CH5
AEADC *ADCPERIPHERAL1_Name_CH5 = nullptr; 
#endif

#endif
 
 

#ifdef UARTPERIPHERAL1
UARTPERIPHERAL1* UARTPERIPHERAL1_Instance = UARTPERIPHERAL1::getInstance();   
AEUART* UARTPERIPHERAL1_Name = nullptr;
#endif 
#ifdef UARTPERIPHERAL2
UARTPERIPHERAL2* UARTPERIPHERAL2_Instance = UARTPERIPHERAL2::getInstance();   
AEUART* UARTPERIPHERAL2_Name = nullptr;
#endif 
#ifdef UARTPERIPHERAL3
UARTPERIPHERAL3* UARTPERIPHERAL3_Instance = UARTPERIPHERAL3::getInstance();   
AEUART* UARTPERIPHERAL3_Name = nullptr;
#endif 
#ifdef UARTPERIPHERAL4
UARTPERIPHERAL4* UARTPERIPHERAL4_Instance = UARTPERIPHERAL4::getInstance();   
AEUART* UARTPERIPHERAL4_Name = nullptr;
#endif 
#ifdef UARTPERIPHERAL5
UARTPERIPHERAL5* UARTPERIPHERAL5_Instance = UARTPERIPHERAL5::getInstance();   
AEUART* UARTPERIPHERAL5_Name = nullptr;
#endif 
#ifdef UARTPERIPHERAL6
UARTPERIPHERAL6* UARTPERIPHERAL6_Instance = UARTPERIPHERAL6::getInstance();   
AEUART* UARTPERIPHERAL6_Name = nullptr;
#endif 




#ifdef I2CPERIPHERAL1
I2CPERIPHERAL1* I2CPERIPHERAL1_Instance = I2CPERIPHERAL1::getInstance();   
AEI2C* I2CPERIPHERAL1_Name = nullptr;
#endif 
#ifdef I2CPERIPHERAL2
I2CPERIPHERAL2* I2CPERIPHERAL2_Instance = I2CPERIPHERAL2::getInstance();   
AEI2C* I2CPERIPHERAL2_Name = nullptr;
#endif 
#ifdef I2CPERIPHERAL3
I2CPERIPHERAL3* I2CPERIPHERAL3_Instance = I2CPERIPHERAL3::getInstance();   
AEI2C* I2CPERIPHERAL3_Name = nullptr;
#endif 


#ifdef SPIPERIPHERAL1
SPIPERIPHERAL1* SPIPERIPHERAL1_Instance = SPIPERIPHERAL1::getInstance();   
AESPI* SPIPERIPHERAL1_Name = nullptr;
#endif  
#ifdef SPIPERIPHERAL2
SPIPERIPHERAL2* SPIPERIPHERAL2_Instance = SPIPERIPHERAL2::getInstance();   
AESPI* SPIPERIPHERAL2_Name = nullptr;
#endif 
#ifdef SPIPERIPHERAL3
SPIPERIPHERAL3* SPIPERIPHERAL3_Instance = SPIPERIPHERAL3::getInstance();   
AESPI* SPIPERIPHERAL3_Name = nullptr;
#endif  


#ifdef PWMPERIPHERAL1
PWMPERIPHERAL1* PWMPERIPHERAL1_Instance = PWMPERIPHERAL1::getInstance();   
AEPWM* PWMPERIPHERAL1_Name = nullptr;
#endif   
#ifdef PWMPERIPHERAL2
PWMPERIPHERAL2* PWMPERIPHERAL2_Instance = PWMPERIPHERAL2::getInstance();   
AEPWM* PWMPERIPHERAL2_Name = nullptr;
#endif   
#ifdef PWMPERIPHERAL3
PWMPERIPHERAL3* PWMPERIPHERAL3_Instance = PWMPERIPHERAL3::getInstance();   
AEPWM* PWMPERIPHERAL3_Name = nullptr;
#endif   
#ifdef PWMPERIPHERAL4
PWMPERIPHERAL4* PWMPERIPHERAL4_Instance = PWMPERIPHERAL4::getInstance();   
AEPWM* PWMPERIPHERAL4_Name = nullptr;
#endif   
#ifdef PWMPERIPHERAL5
PWMPERIPHERAL5* PWMPERIPHERAL5_Instance = PWMPERIPHERAL5::getInstance();   
AEPWM* PWMPERIPHERAL5_Name = nullptr;
#endif   
#ifdef PWMPERIPHERAL6
PWMPERIPHERAL6* PWMPERIPHERAL6_Instance = PWMPERIPHERAL6::getInstance();   
AEPWM* PWMPERIPHERAL6_Name = nullptr;
#endif   



#ifdef USING_AEI2C 
uint8_t AEI2C::TotalNumOfI2cID = 0;
#endif