################################################ 
#this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
################################################


set(INTEGRATION_TESTS CGENTest2)
add_compile_definitions(INTEGRATION_TESTS__${INTEGRATION_TESTS})
add_compile_definitions(INTEGRATION_TEST_CHOSEN="CGENTest2")
set(INTEGRATION_TESTS_FOR_CGENTest2 default2)
add_compile_definitions(INTEGRATION_TESTS_FOR_CGENTest2__${INTEGRATION_TESTS_FOR_CGENTest2})
add_compile_definitions(INTEGRATION_TEST_CHOSEN_SPECIFIC="default2")
add_compile_definitions(CGEN_ALLOPTIONS="")

set(INTEGRATION_TARGET_DIRECTORY "C:/CodeGenerator/CodeGenerator/macro2Test/CGENTest2")


#macro(Target_Directory_Chooser)
		#set(options)
		#set(oneValueArgs TARGET_NAME )
		#set(multiValueArgs )
		#cmake_parse_arguments(_arg "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
#
        #if(${_arg_TARGET_NAME} STREQUAL "exeHalTest")
        #set(INTEGRATION_TARGET_DIRECTORY "C:/AERTOS/AERTOS/src/AE/hal/exeHalTest")
        #elseif(${_arg_TARGET_NAME} STREQUAL "AECoreTestEXE")
        #set(INTEGRATION_TARGET_DIRECTORY "C:/AERTOS/AERTOS/src/AE/AECoreTestEXE")
        #elseif(${_arg_TARGET_NAME} STREQUAL "CGENTest2")
        #set(INTEGRATION_TARGET_DIRECTORY "C:/AERTOS/AERTOS/src/AE/CGENTest2")
        #elseif(${_arg_TARGET_NAME} STREQUAL "CGENTest2")
        #set(INTEGRATION_TARGET_DIRECTORY "C:/CodeGenerator/CodeGenerator/macro2Test/CGENTest2")
        #endif()
#
#endmacro()