

Cgen_Start(CGEN_PROJECT_DIRECTORY "${INTEGRATION_TARGET_DIRECTORY}")

#set(AE_PROJECT_NAME exeHalTest)

Cgen_Option(
        NAME INTEGRATION_TESTS
        DESCRIPTION "choose an integration test directory to build"
        POSSIBLEVALUES ${INTEGRATION_TARGET_NAME}  #AECoreTestEXE AEHal_Tests1
        CONSTRICTS_LATER_OPTIONS
)


 CREATE_TARGET_INTEGRATIONEXE(NAME_OF_TARGET exeHalTest
 LOCATION_OF_TARGET ${INTEGRATION_TARGET_DIRECTORY}#"C:/AERTOS/src/AE/hal"
 LibrariesToLinkTo AECoreLib AEHalLib   
 LIST_OF_TESTS ADC_TEST UART_TEST I2C_TEST
 ) 

 CGEN_END()