//generated file: C:/AERTOS/AERTOS/src/AE/hal/AEHalTests\ADC_TEST.cpp
//**********************************************************************
//this is an auto-generated file using the template file located in the directory of C:\CodeGenerator\CodeGenerator\bin\Debug\..\..\FileTemplates\Files
//ONLY WRITE CODE IN THE UserCode_Section BLOCKS
//If you write code anywhere else,  it will be overwritten. modify the actual template file if needing to modify code outside usersection blocks.

//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################


 
#if INTEGRATION_TESTS_FOR_AEHalTests__ADC_TEST
 
#include "IntegTestPipeline.h"


#include "AECore.h"
#include "AE_Init.h" 
#include "AEClock.h" 
#include "AEObjects.h" 

DECLARE_ALL_AO_PTR





//UserCode_Sectiona
	
uint32_t adcCountToPrint1 = 0;
uint32_t adcCountToPrint2 = 0;
uint32_t adcCountToPrint3 = 0;
//UserCode_Sectiona_end

void RunSelectedIntegrationTest_ADC_TEST()
{

AE_Init();
 //UserCode_Sectionbeforemain
	
	
	AEITEST_END_TestsAfterTimer_AEHalTests(5000) 
		  
	 AEITEST_EXPECT_TEST_TO_RUN_AEHalTests("ADC1 test")  
	 
		
	ADCPERIPHERAL_inst1_ch1->SetADC_ConvCpltCallback_t([]()->void {
		adcCountToPrint1++;
		if (adcCountToPrint1 > 1000)
		{
			uint16_t adcValue = ADCPERIPHERAL_inst1_ch1->GetADCData();
			//! [integ test assert]
			AEITEST_AEHalTests("ADC1 test", (adcValue > 1800 && adcValue < 2500), "test adc1 is getting adc value");
			//! [integ test assert]
			AEPrint("adc1 data is %d \n", adcValue);
			adcCountToPrint1 = 0;
		}
	});
	
	ADCPERIPHERAL_inst1_ch2->SetADC_ConvCpltCallback_t([]()->void {
		adcCountToPrint2++;
		if (adcCountToPrint2 > 1000)
		{
			uint16_t adcValue = ADCPERIPHERAL_inst1_ch2->GetADCData();
			AEITEST_AEHalTests("ADC2 test", (adcValue > 900 && adcValue < 1500), "test adc2 is getting adc value");
			AEPrint("adc2 data is %d \n", adcValue);
			adcCountToPrint2 = 0;
		}
	});
	
	ADCPERIPHERAL_inst1_ch3->SetADC_ConvCpltCallback_t([]()->void {
		//		if (adc3->GetADCData() > 2000)
		//		{ GpioLed1->GPIO_SetHigh(); }
		//		else
		//		{ GpioLed1->GPIO_SetLow(); }
		adcCountToPrint3++;
		if (adcCountToPrint3 > 1000)
		{
			uint16_t adcValue = ADCPERIPHERAL_inst1_ch3->GetADCData();
			AEITEST_AEHalTests("ADC3 test", (adcValue > 1600 && adcValue < 2300), "test adc3 is getting adc value");
			AEPrint("adc3 data is %d \n", adcValue);
			adcCountToPrint3 = 0;
		}
	});
	
//UserCode_Sectionbeforemain_end







//UserCode_Sectionbeforelinks
//UserCode_Sectionbeforelinks_end


//UserCode_Sectionbeforeclock
//UserCode_Sectionbeforeclock_end


//AEITEST_END_TestsAfterTimer_AEHalTests(5000);
//UserCode_Sectionb
//UserCode_Sectionb_end

AEAO::ConfigureAndStart();
}


//UserCode_Sectionc
//UserCode_Sectionc_end





#endif