//generated file: C:/AERTOS/AERTOS/src/AE/hal/AEHalTests\UART_TEST.cpp
//**********************************************************************
//this is an auto-generated file using the template file located in the directory of C:\CodeGenerator\CodeGenerator\bin\Debug\..\..\FileTemplates\Files
//ONLY WRITE CODE IN THE UserCode_Section BLOCKS
//If you write code anywhere else,  it will be overwritten. modify the actual template file if needing to modify code outside usersection blocks.

//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################


 
#if INTEGRATION_TESTS_FOR_AEHalTests__UART_TEST
 
#include "IntegTestPipeline.h"


#include "AECore.h"
#include "AE_Init.h" 
#include "AEClock.h" 
#include "AEObjects.h" 

DECLARE_ALL_AO_PTR





//UserCode_Sectiona
//UserCode_Sectiona_end

void RunSelectedIntegrationTest_UART_TEST()
{

AE_Init();
 //UserCode_Sectionbeforemain
	AEITEST_END_TestsAfterTimer_AEHalTests(5000)
		
AEITEST_EXPECT_TEST_TO_RUN_AEHalTests("TXCMPLT callback");
		
	
	
	UARTPERIPHERAL_inst2->SetRxCpltCallback([](char* msgReceived, uint32_t sizeOfReceivedMsg)->void {
		AEPrint("message received for uart: %s \n", msgReceived);
		//uart1->TansmitMsg("message received from uart: %s \n", 20);
		//GpioLed1->GPIO_TogglePin();
		
	}); 
	UARTPERIPHERAL_inst2->SetTxCpltCallback([]()->void {
		AEPrint("transfer complete \n"); 
		AEITEST_AEHalTests("TXCMPLT callback", true, "tx complete");
		
	});
	
	UARTPERIPHERAL_inst2->TansmitMsg("hello", 5);
	
//UserCode_Sectionbeforemain_end







//UserCode_Sectionbeforelinks
//UserCode_Sectionbeforelinks_end


//UserCode_Sectionbeforeclock
//UserCode_Sectionbeforeclock_end


//AEITEST_END_TestsAfterTimer_AEHalTests(5000);
//UserCode_Sectionb
//UserCode_Sectionb_end

AEAO::ConfigureAndStart();
}


//UserCode_Sectionc
//UserCode_Sectionc_end





#endif